name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - released
  workflow_dispatch: {}

env:
  # See https://github.com/nodejs/release#release-schedule
  # Node.js v20 EOL = 2026-04-30. v22 EOL = 2027-04-30. v23 EOL = 2025-06-01. v24 EOL = 2028-04-30.
  NODE_BUILD_CMD: npx --no-install prebuild -r node -t 24.0.0 --include-regex 'better_sqlite3.node$'

  # See https://www.electronjs.org/docs/latest/tutorial/electron-timelines#version-support-policy
  # Electron v29 EOL = 2024-08-20. v30 EOL = 2024-10-15. v31 EOL = 2025-01-14. v32 EOL = 2025-03-11. v33 EOL = 2025-05-13. v34 EOL = 2025-06-24. v35 EOL = 2025-09-02. v36 EOL = 2025-10-28.
  ELECTRON_BUILD_CMD: npx --no-install prebuild -r electron -t 29.0.0 -t 30.0.0 -t 31.0.0 -t 32.0.0 -t 33.0.0 -t 34.0.0 -t 35.0.0 -t 36.0.0 --include-regex 'better_sqlite3.node$'

jobs:
  prebuild-linux-x64:
    permissions: write-all
    name: Prebuild on Linux x64
    runs-on: ubuntu-latest
    container: node:20-bullseye
    steps:
      - uses: actions/checkout@v4
      - run: npm install --ignore-scripts
      - run: ${{ env.NODE_BUILD_CMD }}
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: prebuilds
          if-no-files-found: error
          retention-days: 7
